### ISSUE TITLE
Clean saves of modded content that no longer is loaded

### ISSUE THREAD

**Issue by mpstark** [BattletechModders/ModTek#106]
Discussion with @m22spencer. `SimGameState.Hydrate` and `CombatGameState.Hydrate` are good starting points.

**Comment by CptMoore** [comment]
An alternative is something that is currently in MechEngineer.
MechEngineer has a feature that redirects save data to a directory.
Types of data supported: cloud, local, cached settings (skirmish mech loadouts)

```
    "NewSaveFolder" : {
        "Enabled" : false,
        "EnabledDescription" : "Redirects all save operations to use one folder for all save related data.",
        "Path" : "Mods/Saves"
    },
```

**Comment by CptMoore** [comment]
see https://github.com/BattletechModders/NewSaveFolder

HBS does allow to "fix" broken mechs and has some support for mods due to modloader, but a save redirection is still required to allow multiple mod installs to coexist (through moving in and out the save folder).
I think anything that would fix this would need to introduce an ability to switch between BTA and RT.. so gl.
