### ISSUE TITLE
v3.1.##: Odd logger behavior

### ISSUE THREAD

**Issue by korgano** [BattletechModders/ModTek#214]
Symptoms:
- ModTek repeatedly changes log level settings for various loggers (see example below)
- Said loggers generally fail to produce actual log outputs at any log level

```
16:22:02.1419341 ModTek [TRACE] Log Level of logger name=CombatLog.Heat changed from level=null to level=DEBUG(0)
16:22:02.1419586 DebugBridge [LOG] Set Logger CombatLog.Heat to LogLevel Debug
16:22:06.1726409 ModTek [TRACE] Log Level of logger name=CombatLog.Heat changed from level=DEBUG(0) to level=null
16:22:06.1882739 ModTek [TRACE] Log Level of logger name=CombatLog.Heat changed from level=null to level=ERROR(3)
```

(Full battletech_log here: [battletech_log.txt](https://github.com/BattletechModders/ModTek/files/10482509/battletech_log.txt))

Possibly related is a ModTek fatal error: 
[ModTekFatalError.txt](https://github.com/BattletechModders/ModTek/files/10482503/ModTekFatalError.txt)

Also possibly related is `ModTek/config.json` file only containing `{}` and no actual configuration settings.

Once in-game, most .DLL Harmony patches will execute, but .DLLs with integrated loggers that interact with functions like `CombatLog` will not generate output, making diagnosing errors impossible.

**Comment by CptMoore** [comment]
- ModTek does not change the log level, but it observes a change happening. A logger gets initialized with a default log level and later HBS code reloads all logger levels due to the debug settings. Its a bit chatty, but it helps with knowing what actually was changed and what the end result is. One can even set`DebugLogLevelSetters` to true in the loggersettings sectio to see a stack trace of who sets the log level.
- `BATTLETECH\BattleTech_Data\StreamingAssets\data\debug\settings.json` contains the target log levels for non-ModTek logs (ModTek managed its own 4 loggers directly, see override settings in help.json).
- Depending on the log level, nothing might actually be logged, depends on HBS or the mod.
- I've now added (latest release) a try catch around the UnityStackTrace.ToString exception, hopefully those cases are rare.
- `ModTek/config.json` only contains key/values that override the defaults in `ModTek/config.help.json`, if its empty it means you are using the defaults.

**Comment by korgano** [comment]
Latest preview release seems to have completely fixed the issue with UnityStackTrace.ToString. I have run multiple sessions and not encountered the fatal error since updating to v3.1.15+3. This issue seems to be solved.

> ModTek/config.json only contains key/values that override the defaults in ModTek/config.help.json, if its empty it means you are using the defaults.
This is non-obvious behavior that is very confusing, so it might be good to update the installation documentation to explain this.

Since
