### ISSUE TITLE
Unsure if Modtech loads.

### ISSUE THREAD

**Issue by Supermagnum** [BattletechModders/ModTek#238]
Hi,- I have a problem with Modtech .  I am running Steam on Linux.  I have set  the launch options to ./run.sh %command%  .
I cant see /W MODTEK  in the bottom left corner of the main menu.  Only 1.9.1-686BR . 
Debug: https://pastebin.com/Y4RFDJ18

**Comment by CptMoore** [comment]
I am also running ModTek under Steam, but I am not using Proton. If you are using Proton (looks like it) you should not use run.sh as that is for actual native Linux installations. For Proton you might need to setup the wine prefix in a way that it loads `winhttp.dll`, since that is UnityDoorstop which starts ModTek. Setup Proton/Wine via Steam is something I have not done and can't help. If you can, switch to the native installation, otherwise you can search for help about UnityDoorstop in the internet or at the BepInEx mod utilities umbrella, e.g. https://docs.bepinex.dev/v5.4.16/articles/advanced/proton_wine.html

**Comment by Supermagnum** [comment]
I was using proton,- issue solved. 
Thanks.
