### ISSUE TITLE
Adjust Save Game Location for Modded Content

### ISSUE THREAD

**Issue by Mpstark** [BattletechModders/ModTek#36]
Since the vanilla game breaks currently with saves that contain uninstalled mod content, redirect saves to another location and only give the game saves that it can process.

**Comment by CptMoore** [comment]
would it make sense to warn the user (e.g. in the version number in the menu) about mods making save games that are not vanilla compatible?

**Comment by Mpstark** [comment]
It does make sense to warn the user somewhere -- prob not in the version number, but in the save menu.

**Comment by m22spencer** [comment]
Some discussion on the following would be good before implementation.  Otherwise, we just end up with the original problem but in our mod specific folder.

- Migration
  - Vanilla -> Mod specific save
  - ModV1 -> ModV2   (upgraders)
  - ModV2 -> ModV1   (downgraders)
- Separation of mod saves
  - How do we identify when to make a new "identity" based on the current mod configuration.

**Comment by Mpstark** [comment]
I don't believe that this is the way forward, tbh, closing issue for now. I'd greatly prefer cleaning saves.
