### ISSUE TITLE
Support multiple dlls and settings in single mod.json

### ISSUE THREAD

**Issue by Mpstark** [BattletechModders/ModTek#45]

**Comment by CptMoore** [comment]
whats the use case for this? seems redundant as one can always create a dll to use several dlls in the same mod.

**Comment by Mpstark** [comment]
It's not high on the priority list, but you could package together several mod .dlls under a single mod folder with a unified `mod.json` that collects all of the settings together. Like a compilation or something. Someone on discord mentioned it, it didn't sound like something that I would do myself, but having the option open doesn't pain me or anything.

**Comment by Sheep-y** [comment]
I think splitting the mod.json is a good idea because each DLL will expect their own setting string.

The only advantage I see in consolidating them into one file is to make it easy to disable them all in one file, but it's something that I prefer to be solved by a future GUI instead of by complicating mod structure.
